name: ELEC3644 Server Deployment

on: [ push, pull_request ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Push to GitHub
        continue-on-error: true
        run: |
          git config --global user.name 'Build Action'
          git config --global user.email '<>'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit -am "chore: build"
          git push
          

      - name: Push to remote repository - production
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH }}
          script: |
            cd /home/ubuntu/ELEC3644-Property-App-Server
            git pull
            /home/ubuntu/.nvm/versions/node/v23.0.0/bin/npm install
